### ISSUE TITLE
加载问题

### ISSUE THREAD

**Issue by Adamyang666** [kevinfaveri/vue-twemoji-picker#107]
[表情加载不出来，是服务器问题吗]
![313f2becdbb721b774146046f3669d7](https://user-images.githubusercontent.com/56759481/211711019-347cece5-2186-4f58-9dcf-72559e0ac165.png)

**Comment by Adamyang666** [comment]
> 表情加载不出来，是服务器问题吗

**Comment by 13g10n** [comment]
Hi @Adamyang666!

Please refer to [my PR](https://github.com/kevinfaveri/vue-twemoji-picker/pull/108), it also contains hotfix for existing version

**Comment by Adamyang666** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by webpon** [comment]
i also meet this problem

**Comment by Adamyang666** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by jayeshtechextensor** [comment]
@webpon Are you resolved this issue?

**Comment by Adamyang666** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by 13g10n** [comment]
> @webpon Are you resolved this issue?

As I mentioned before, currently you can use `twemojiPath` param:

```js
<twemoji-picker
    ...
    twemojiPath="https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/"
>
```

**Comment by Adamyang666** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
