### ISSUE TITLE
Broken emojis

### ISSUE THREAD

**Issue by JoseIsra** [kevinfaveri/vue-twemoji-picker#110]
Hi, recently the emojis are broken but they can be picked. All the emojis has a broken image. Is a problem with the library? Even in the documentation page are broken. 
This is a screenshot from the documentation itself here: https://kevinfaveri.github.io/vue-twemoji-picker/docs/#requirements

![image](https://user-images.githubusercontent.com/67303431/220950698-077f9482-3b2e-4af9-a148-fb9750203ce8.png)

Any idea will be useful, thanks

**Comment by jarooda** [comment]
> I have the same issue, still trying to investigate. Did you find why
> 
> EDIT: for anyone who stumble here, just add the below to the twemoji-picker component
> 
> ```
> twemojiPath="https://cdn.jsdelivr.net/npm/twemoji@11.3.0/2/"
> twemojiExtension=".svg"
> twemojiFolder="svg"
> ```

Thanks, its work, but some emoji still broken

<img width="253" alt="Screenshot 2023-03-14 at 10 22 26" src="https://user-images.githubusercontent.com/71919479/224884970-5553f4ef-df56-45ee-b314-e7e603510972.png">

**Comment by oriongunning** [comment]
> > I have the same issue, still trying to investigate. Did you find why
> > EDIT: for anyone who stumble here, just add the below to the twemoji-picker component
> > ```
> > twemojiPath="https://cdn.jsdelivr.net/npm/twemoji@11.3.0/2/"
> > twemojiExtension=".svg"
> > twemojiFolder="svg"
> > ```
> 
> Thanks, its work, but some emoji still broken
> 
> <img alt="Screenshot 2023-03-14 at 10 22 26" width="253" src="https://user-images.githubusercontent.com/71919479/224884970-5553f4ef-df56-45ee-b314-e7e603510972.png">

Yes, same issue for me, but I'm not sure how to fix that...

**Comment by Klmnko** [comment]
> > > I have the same issue, still trying to investigate. Did you find why
> > > EDIT: for anyone who stumble here, just add the below to the twemoji-picker component
> > > ```
> > > twemojiPath="https://cdn.jsdelivr.net/npm/twemoji@11.3.0/2/"
> > > twemojiExtension=".svg"
> > > twemojiFolder="svg"
> > > ```
> > 
> > 
> > Thanks, its work, but some emoji still broken
> > <img alt="Screenshot 2023-03-14 at 10 22 26" width="253" src="https://user-images.githubusercontent.com/71919479/224884970-5553f4ef-df56-45ee-b314-e7e603510972.png">
> 
> Yes, same issue for me, but I'm not sure how to fix that...

from issue https://github.com/twitter/twemoji/issues/580,
try this one https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/, works for me

**Comment by kevinfaveri** [comment]
Hotfixed on #108
