### ISSUE TITLE
Recalculate pickerPaddingOffset method

### ISSUE THREAD

**Issue by Quasarman** [kevinfaveri/vue-twemoji-picker#67]
There seems to be no way to change the paddingOffset when the picker was opened once since it gets set only in the mounted function. It would be nice to have a methon which one can call via .refs to set the pickerPaddingOffset once the picker has been opened.

This can be usefull when for example havin a custom input below the picker that changes in size when writing a message and wanting the picker to stay open while a message is written.

**Comment by kevinfaguiar** [comment]
Hmm.. I don't think a method is the best way here. It is a bug in fact: using Vue logic this prop should be reactive. I'm working on a solution where **pickerPaddingOffset** will be applied to the picker when changed.

**Comment by Quasarman** [comment]
Alright, thanks for the update!

**Comment by Quasarman** [comment]
Hello @kevinfaguiar,
Any updates on this?

**Comment by kevinfaguiar** [comment]
Hi there @Quasarman! 

The last two months have been a wild ride and I did not have time to focus on this project, sorry :(

I'm planning to begin working again to tackle some issues, like this one, next week.

Again, sorry for letting you down on this :(

**Comment by Quasarman** [comment]
Hey @kevinfaguiar,

no worries, its not a really pressing issue. Sometimes with work, studying and wanting to keep a healthy social life, I do not find the time to make progress on my private projects as well.

Please take your time with it, all in all twemoji picker is already awesome as is! Well implemented, nicely documented and with a great support.

Cheers,
Johannes
