### ISSUE TITLE
Character count of emojis and chinese characters will be equal to 1

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [kevinfaveri/vue-twemoji-picker#80]
Hello,

I am pretty aware that you applied the **twitter-text** for the content length counting but can we have an option to make every count just 1. 

**Example:**
- If I add an emoticon then just add 1 count
- If I add chinese characters such as 好得. The count will be 2

**Comment by Dean-Christian-Armada** [comment]
Sorry but what is OSS?

**Comment by kevinfaguiar** [comment]
Open-source software hehe

**Comment by kevinfaveri** [comment]
Fixed by https://github.com/kevinfaveri/vue-twemoji-picker/pull/86
